name: Run FaDIn tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  unittest:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            version_python: 3.9
            coverage: 'true'
          - os: ubuntu-latest
            version_python: "3.10"
          - os: macos-latest
            version_python: 3.9
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.version_python }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install torch --extra-index-url https://download.pytorch.org/whl/cpu
        python -m pip install -e .[test]
    - name: Test with pytest
      run: |
        pytest
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.version_python }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ruff
    - name: Lint with Ruff
      run: |
        ruff check .
